# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[edge_functions]]
  function = "aiResponse"
  path = "/aiResponse"

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
